### ISSUE TITLE
About evaluation on document classification

### ISSUE THREAD

**Issue by iwangjian** [XunGuangxu/2in1#1]
Hi, there is no training data and test data splitting in your script **_eval_topic_class.py_** when evaluate on document classification, is it OK when just training on the whole **_theta_** file?

**Comment by Xshelton** [comment]
hi，there. I have some questions too.Maybe we can talk about it..
did u run the whole program?emm, for me, it seems that the preprocessing lacks some files.
    #dwid_pt = DATA_DIR+'CoEmbedding/doc_id.txt'
    #dwmatrix_pt = DATA_DIR+'CoEmbedding/dw_matrix.csv'
    #voca_pt = DATA_DIR+'CoEmbedding/vocab.txt'
did u find all these document?or shall we just produce them by ourselves?

**Comment by Xshelton** [comment]
Ok， I made a mistake ,I found that I just didn't complete buliding up the whole folder and text needed.

**Comment by GT-TOP** [comment]
hi, i'm confused how to run the whole project?

**Comment by XunGuangxu** [comment]
You can just run main.py to run the whole project.

**Comment by XunGuangxu** [comment]
> Hi, there is no training data and test data splitting in your script **_eval_topic_class.py_** when evaluate on document classification, is it OK when just training on the whole **_theta_** file?

Hi, I think it is okay to do so. Because the purpose is to show that the learned topic representations are reasonable and discriminative, not to evaluate the classifier algorithm.
